# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jim Kaczmarek for Sheriff
email: mollykaczmarek@live.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Global Variables
facebook_username:
facebook_page: https://www.facebook.com/people/Jim-Kaczmarek/100011835361954
treasurer_email: kendra@thehighcountry.net
treasurer_phone: '(208) 392-6653'

# Where things are.
include: ['_pages']

# Collections
collections:
  events:
    output: true
    permalink: /events/:title/

assets:
  prefix: "/assets"
  sources:
    -   _assets/css
    -   _assets/img
    -   _assets/js
  compress:
    css: sass
    js: uglifier
  features:
    automatic_img_alt: true
    automatic_img_size: false

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-assets]
